
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.Timer;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUKHLIS
 */
public class Jtic extends javax.swing.JFrame {

    private Jintro intro;
    int pX,pY;
    
    int  Activate=1;
     boolean b1;
     Color myc = new Color(204,204,204);
    
     boolean b2;
     boolean b3;
     boolean b4;
     boolean b5;
     boolean b6;
     boolean b7;
     boolean b8;
     boolean b9;
    public Jtic() {
        initComponents();
        setIcon();
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jexit = new javax.swing.JLabel();
        jminimize = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        j1 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        jr = new javax.swing.JLabel();
        jexitbutton = new javax.swing.JButton();
        jpa = new javax.swing.JButton();

        setFocusCycleRoot(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Entypo_f32a(0)_48.png"))); // NOI18N
        jLabel2.setText("Tic-Tac-Toe");

        jexit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jexit.setForeground(new java.awt.Color(204, 204, 204));
        jexit.setText("x");
        jexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jexitMouseClicked(evt);
            }
        });

        jminimize.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jminimize.setForeground(new java.awt.Color(204, 204, 204));
        jminimize.setText("-");
        jminimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jminimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jminimize)
                .addGap(18, 18, 18)
                .addComponent(jexit)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jexit)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jminimize, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        j1.setBackground(new java.awt.Color(102, 102, 102));
        j1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        j1.setBorder(null);
        j1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        j1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1MouseClicked(evt);
            }
        });
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setBackground(new java.awt.Color(102, 102, 102));
        j2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        j2.setBorder(null);
        j2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2MouseClicked(evt);
            }
        });
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        j3.setBackground(new java.awt.Color(102, 102, 102));
        j3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        j3.setBorder(null);
        j3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3MouseClicked(evt);
            }
        });
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        j4.setBackground(new java.awt.Color(102, 102, 102));
        j4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        j4.setBorder(null);
        j4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4MouseClicked(evt);
            }
        });
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        j5.setBackground(new java.awt.Color(102, 102, 102));
        j5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        j5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j5MouseClicked(evt);
            }
        });
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        j6.setBackground(new java.awt.Color(102, 102, 102));
        j6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        j6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j6MouseClicked(evt);
            }
        });
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        j7.setBackground(new java.awt.Color(102, 102, 102));
        j7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        j7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j7MouseClicked(evt);
            }
        });
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });

        j8.setBackground(new java.awt.Color(102, 102, 102));
        j8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        j8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j8MouseClicked(evt);
            }
        });
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });

        j9.setBackground(new java.awt.Color(102, 102, 102));
        j9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        j9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j9MouseClicked(evt);
            }
        });
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });

        p1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p1.setForeground(new java.awt.Color(204, 204, 204));
        p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        p2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p2.setForeground(new java.awt.Color(204, 204, 204));
        p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jr.setForeground(new java.awt.Color(204, 204, 204));
        jr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jexitbutton.setBackground(new java.awt.Color(102, 102, 102));
        jexitbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jexitbutton.setForeground(new java.awt.Color(204, 204, 204));
        jexitbutton.setText("New Player");
        jexitbutton.setBorder(null);
        jexitbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jexitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitbuttonActionPerformed(evt);
            }
        });

        jpa.setBackground(new java.awt.Color(102, 102, 102));
        jpa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jpa.setForeground(new java.awt.Color(204, 204, 204));
        jpa.setText("Play Again");
        jpa.setBorder(null);
        jpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jpa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jexitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jr, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(j8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jr, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jexitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jexitMouseClicked

    private void jminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jminimizeMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        setLocation(getLocation().x+evt.getX()-pX, getLocation().y+evt.getY()-pY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        pX=evt.getX();
        pY=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void j1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseClicked

        
    }//GEN-LAST:event_j1MouseClicked

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        if(Activate==1){
            j1.setText("X");
            Activate=2;
            j1.setEnabled(false);
            
            
        }else
        if(Activate==2){
            j1.setText("O");
            Activate=1;
            j1.setEnabled(false);
            
        }
    }//GEN-LAST:event_j1ActionPerformed

    private void j2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseClicked
        
    }//GEN-LAST:event_j2MouseClicked

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        if(Activate==1){
            j2.setText("X");
            p2.setForeground(myc);
            Activate=2;
            j2.setEnabled(false);
            
        }else
        if(Activate==2){
            j2.setText("O");
            p1.setForeground(myc);
            Activate=1;
            j2.setEnabled(false);
        }
    }//GEN-LAST:event_j2ActionPerformed

    private void j3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseClicked
        
    }//GEN-LAST:event_j3MouseClicked

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        if(Activate==1){
            j3.setText("X");
            Activate=2;
            j3.setEnabled(false);
            
            
        }else
        if(Activate==2){
            j3.setText("O");
            Activate=1;
            j3.setEnabled(false);
            double opacity = 0.5;
            j3.setOpaque(false);
        }
    }//GEN-LAST:event_j3ActionPerformed

    private void j4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseClicked
        
    }//GEN-LAST:event_j4MouseClicked

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        if(Activate==1){
            j4.setText("X");
            Activate=2;
            j4.setEnabled(false);
            

        }else
        if(Activate==2){
            j4.setText("O");
            Activate=1;
            j4.setEnabled(false);
        }
    }//GEN-LAST:event_j4ActionPerformed

    private void j5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j5MouseClicked
        
    }//GEN-LAST:event_j5MouseClicked

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        if(Activate==1){
            j5.setText("X");
            
            Activate=2;
            j5.setEnabled(false);
            

        }else
        if(Activate==2){
            j5.setText("O");
            Activate=1;
            j5.setEnabled(false);
        }
    }//GEN-LAST:event_j5ActionPerformed

    private void j6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j6MouseClicked
        
    }//GEN-LAST:event_j6MouseClicked

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        if(Activate==1){
            j6.setText("X");
            Activate=2;
            j6.setEnabled(false);

        }else
        if(Activate==2){
            j6.setText("O");
            Activate=1;
            j6.setEnabled(false);
        }
    }//GEN-LAST:event_j6ActionPerformed

    private void j7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j7MouseClicked
      
    }//GEN-LAST:event_j7MouseClicked

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        if(Activate==1){
            j7.setText("X");
            Activate=2;
            j7.setEnabled(false);
        }else
        if(Activate==2){
            j7.setText("O");
            Activate=1;
            j7.setEnabled(false);
        }
    }//GEN-LAST:event_j7ActionPerformed

    private void j8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseClicked
      
    }//GEN-LAST:event_j8MouseClicked

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        if(Activate==1){
            j8.setText("X");
            j8.setEnabled(false);
            Activate=2;
        }else
        if(Activate==2){
            j8.setText("O");
            Activate=1;
            j8.setEnabled(false);
        }
    }//GEN-LAST:event_j8ActionPerformed

    private void j9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j9MouseClicked
     
    }//GEN-LAST:event_j9MouseClicked

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        if(Activate==1){
            j9.setText("X");
            Activate=2;
            j9.setEnabled(false);

        }else
        if(Activate==2){
            j9.setText("O");
            Activate=1;
            j9.setEnabled(false);
        }
    }//GEN-LAST:event_j9ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Timer timer=new Timer(1,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(Activate==1){
                    p1.setForeground(Color.red);
                    p2.setForeground(myc);
                    
                    p1.setBorder(BorderFactory.createLineBorder(Color.red));
                    p2.setBorder(BorderFactory.createEmptyBorder());
                }
                else if(Activate==2){
                    p2.setForeground(Color.red);
                    p1.setForeground(myc);
                  
                    p2.setBorder(BorderFactory.createLineBorder(Color.red));
                    p2.setBorder(BorderFactory.createLineBorder(Color.red));
                    p1.setBorder(BorderFactory.createEmptyBorder());
                    
                }
                if((j1.getText()=="X")&&(j2.getText()=="X")&&(j3.getText()=="X")){
                    p1.setForeground(myc);
                    p2.setForeground(myc);
                    
                    jr.setText("Congratulations! "+p1.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                     
                     p2.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j1.getText()=="O")&&(j2.getText()=="O")&&(j3.getText()=="O")){
                     p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p2.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                    
                     p1.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j4.getText()=="X")&&(j5.getText()=="X")&&(j6.getText()=="X")){
                   p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p1.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                   
                     p2.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j4.getText()=="O")&&(j5.getText()=="O")&&(j6.getText()=="O")){
                    p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p2.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                 
                     p1.setBorder(BorderFactory.createEmptyBorder());
                    
                }
                else if((j7.getText()=="X")&&(j8.getText()=="X")&&(j9.getText()=="X")){
               p1.setForeground(myc);
                    p2.setForeground(myc);
                    
                    jr.setText("Congratulations!"+p1.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
        
                     p2.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j7.getText()=="O")&&(j8.getText()=="O")&&(j9.getText()=="O")){
                   p1.setForeground(myc);
                    p2.setForeground(myc);p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p2.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                   
                     p1.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j1.getText()=="X")&&(j4.getText()=="X")&&(j7.getText()=="X")){
                 p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p1.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                    
                     p2.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j1.getText()=="O")&&(j4.getText()=="O")&&(j7.getText()=="O")){
                    p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p2.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                   
                     p1.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j2.getText()=="X")&&(j5.getText()=="X")&&(j8.getText()=="X")){
                    p1.setForeground(myc);
                    p2.setForeground(myc);
                    
                    jr.setText("Congratulations! "+p1.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                   
                     p2.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j2.getText()=="O")&&(j5.getText()=="O")&&(j8.getText()=="O")){
                  p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p2.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                   
                     p1.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j3.getText()=="X")&&(j6.getText()=="X")&&(j9.getText()=="X")){
                  p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p1.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                 
                     p2.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j3.getText()=="O")&&(j6.getText()=="O")&&(j9.getText()=="O")){
                    p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p2.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                    
                     
                     p1.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j1.getText()=="X")&&(j5.getText()=="X")&&(j9.getText()=="X")){
                    p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p1.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                 
                     p2.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j1.getText()=="O")&&(j5.getText()=="O")&&(j9.getText()=="O")){
                   p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p2.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                    
                     
                     p1.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j3.getText()=="X")&&(j5.getText()=="X")&&(j7.getText()=="X")){
                    p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p1.getText()+" Win");
                    jr.setForeground(Color.green);
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                    
                     p2.setBorder(BorderFactory.createEmptyBorder());
                }
                else if((j3.getText()== "O")&&(j5.getText()=="O")&&(j7.getText()=="O")){
                    p1.setForeground(myc);
                    p2.setForeground(myc);
                    jr.setText("Congratulations! "+p2.getText()+" Win");
                    jr.setForeground(Color.green);
                    
                    j1.setEnabled(false);
                    j2.setEnabled(false);
                    j3.setEnabled(false);
                    j4.setEnabled(false);
                    j5.setEnabled(false);
                    j6.setEnabled(false);
                    j7.setEnabled(false);
                    j8.setEnabled(false);
                    j9.setEnabled(false);
                    
                     p1.setBorder(BorderFactory.createEmptyBorder());
                }
                
                    
                
                else {
                   
                    b1=j1.isEnabled();
                    b2=j2.isEnabled();
                    b3=j3.isEnabled();
                    b4=j4.isEnabled();
                    b5=j5.isEnabled();
                    b6=j6.isEnabled();
                    b7=j7.isEnabled();
                    b8=j8.isEnabled();
                    b9=j9.isEnabled();
                     if((b1==false)&&(b2==false)&&(b3==false)&&(b4==false)&&(b5==false)&&(b6==false)&&(b7==false)&&(b8==false)&&(b9==false)){
            
                        p1.setForeground(myc);
                        p2.setForeground(myc);
                        jr.setText("Match Is Draw");
                        
                        p2.setBorder(BorderFactory.createEmptyBorder());
            
        }
                     else{
                         jr.setText("Result Shows Here");
                     }
                    
                    
                  
                   
                   
                }
                
            }
        });
        timer.setRepeats(true);
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jexitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitbuttonActionPerformed
        new Jintro().setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_jexitbuttonActionPerformed

    private void jpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpaActionPerformed
        
        j1.setEnabled(true);
        j2.setEnabled(true);
        j3.setEnabled(true);
        j4.setEnabled(true);
        j5.setEnabled(true);
        j6.setEnabled(true);
        j7.setEnabled(true);
        j8.setEnabled(true);
        j9.setEnabled(true);
        j1.setText("");
        j2.setText("");
        j3.setText("");
        j4.setText("");
        j5.setText("");
        j6.setText("");
        j7.setText("");
        j8.setText("");
        j9.setText("");
        jr.setText("Result Shows Here");
        jr.setForeground(myc);
        
        
        
        
        
    }//GEN-LAST:event_jpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jtic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jtic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jtic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jtic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jtic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jexit;
    private javax.swing.JButton jexitbutton;
    private javax.swing.JLabel jminimize;
    private javax.swing.JButton jpa;
    private javax.swing.JLabel jr;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("image.png")));
    }
    public void setp1name(String name){
        p1.setText(name);
    }
    public void setp2name(String name){
        p2.setText(name);
    }

      
}



